name: HAO
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8a8a6'
    - '#cad3d2'
    - '#44372f'
    - '#5d87b5'
    - '#f3f9f7'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
