name: HAO
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: 'HAO '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312726'
    - '#82c1f4'
    - '#bd6528'
    - '#7e563c'
    - '#95908d'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
